[phases.setup]
nixPkgs = ["nodejs_20", "npm", "vips", "pkg-config"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx prisma generate", "npx tsc || true"]

[start]
cmd = "npm start"
